# Generated by Django 2.0.3 on 2018-03-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stub_text', models.CharField(max_length=50, unique=True)),
                ('sim_text', models.CharField(max_length=100)),
                ('board_text', models.CharField(max_length=50)),
                ('ammeter1_text', models.CharField(max_length=50)),
                ('ammeter2_text', models.CharField(max_length=50)),
                ('gun1_text', models.CharField(max_length=50)),
                ('gun2_text', models.CharField(max_length=50)),
                ('gun_vendor_text', models.CharField(max_length=100)),
            ],
        ),
    ]
