# Generated by Django 2.0.3 on 2018-03-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20180323_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_text', models.CharField(default='new record', max_length=50)),
                ('result_bool', models.BooleanField(default=False)),
                ('report_text', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='report product')),
                ('factory_text', models.CharField(max_length=50)),
                ('person_text', models.CharField(max_length=50)),
                ('approved_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='testtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.TestType'),
        ),
    ]
