# Generated by Django 2.0.3 on 2018-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20180325_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='stubinfo',
            name='power_module_text',
            field=models.CharField(choices=[('0', '华为'), ('1', '英可瑞'), ('2', '麦格米特')], default='0', max_length=50, verbose_name='电源模块厂家'),
        ),
    ]
