# Generated by Django 2.0.3 on 2018-03-26 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_stubinfo_power_module_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardinfo',
            options={'verbose_name': '控制盒信息', 'verbose_name_plural': '控制盒信息'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '测试记录', 'verbose_name_plural': '测试记录'},
        ),
        migrations.AlterModelOptions(
            name='stubinfo',
            options={'verbose_name': '充电桩信息', 'verbose_name_plural': '充电桩信息'},
        ),
        migrations.AlterModelOptions(
            name='testtype',
            options={'verbose_name': '测试类型', 'verbose_name_plural': '测试类型'},
        ),
        migrations.AddField(
            model_name='boardinfo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='stubinfo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='approved_bool',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
        migrations.AlterField(
            model_name='record',
            name='factory_text',
            field=models.CharField(max_length=50, verbose_name='工厂'),
        ),
        migrations.AlterField(
            model_name='record',
            name='person_text',
            field=models.CharField(max_length=50, verbose_name='测试人员'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pub_date',
            field=models.DateTimeField(verbose_name='测试时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='report_text',
            field=models.CharField(max_length=250, verbose_name='报表'),
        ),
        migrations.AlterField(
            model_name='record',
            name='result_bool',
            field=models.BooleanField(default=False, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sn_text',
            field=models.CharField(default='new record', max_length=50, verbose_name='测试编号'),
        ),
        migrations.AlterField(
            model_name='record',
            name='testtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.TestType', verbose_name='测试类型'),
        ),
    ]
